# Generated by Django 4.0.5 on 2023-05-31 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_com', models.CharField(max_length=50, verbose_name='Comuna')),
            ],
        ),
        migrations.CreateModel(
            name='estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip_est', models.CharField(max_length=30, verbose_name='Estado reserva')),
            ],
        ),
        migrations.CreateModel(
            name='ficha_pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pet', models.CharField(max_length=60, verbose_name='Nombre mascota')),
                ('especie', models.CharField(max_length=10, verbose_name='Especie')),
                ('raza', models.CharField(blank=True, max_length=20, verbose_name='Raza')),
                ('color', models.CharField(max_length=20, verbose_name='Color mascota')),
                ('genero', models.IntegerField(choices=[[1, 'Hembra'], [2, 'Macho'], [3, 'Indefinido']], verbose_name='género')),
                ('edad', models.IntegerField(blank=True, verbose_name='Edad')),
                ('observ', models.TextField(blank=True, max_length=250, verbose_name='Observaciones')),
                ('castrado', models.IntegerField(choices=[[1, 'Si'], [2, 'No'], [3, 'Por confirmar']], verbose_name='Esterilización')),
                ('imagen', models.ImageField(null=True, upload_to='mascotas')),
                ('contact_emerg', models.CharField(max_length=50, verbose_name='Nombre contacto emergencia')),
                ('num_emerg', models.IntegerField(verbose_name='Número de emergencia')),
            ],
        ),
        migrations.CreateModel(
            name='Hist_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_estadia', models.IntegerField(verbose_name='id historico pagos estadia')),
                ('fecha_pago', models.DateField(verbose_name='fecha pago')),
                ('monto', models.IntegerField(verbose_name='monto')),
            ],
        ),
        migrations.CreateModel(
            name='Hist_reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_hist_est', models.IntegerField(verbose_name='id historico reserva')),
                ('fecha_ini', models.DateField(verbose_name='fecha inicio')),
                ('fecha_term', models.DateField(verbose_name='fecha termino')),
                ('id_cliente', models.IntegerField(verbose_name='id cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=11, unique=True, verbose_name='Rut')),
                ('dv', models.CharField(max_length=1, verbose_name='digito verificador')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombre completo')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('phone', models.IntegerField(verbose_name='Teléfono')),
                ('mail', models.EmailField(max_length=254, verbose_name='Correo')),
                ('direccion', models.CharField(max_length=70, verbose_name='Dirección')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_r', models.CharField(max_length=50, verbose_name='Región')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_suc', models.CharField(max_length=50, verbose_name='Sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=30, null=True, verbose_name='Detalle')),
                ('valor', models.IntegerField(verbose_name='Valor')),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip_vac', models.CharField(max_length=60, verbose_name='Descripción vacunas')),
                ('pendientes', models.IntegerField(choices=[[1, 'Si'], [2, 'No']], verbose_name='Vacunas pendientes')),
                ('f_pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ficha_pet')),
            ],
        ),
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip', models.TextField(max_length=60, verbose_name='Descripción')),
                ('fecha_ini', models.DateField(verbose_name='Fecha ingreso')),
                ('fecha_term', models.DateField(verbose_name='Fecha salida')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.estado')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=30, verbose_name='Cargo')),
                ('profesion', models.CharField(blank=True, max_length=30, verbose_name='Profesion')),
                ('mail_insti', models.EmailField(max_length=254, verbose_name='Correo institucional')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='funcionarios')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.persona')),
                ('sucur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sucursal')),
            ],
        ),
        migrations.AddField(
            model_name='ficha_pet',
            name='dueño',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.persona'),
        ),
        migrations.CreateModel(
            name='estadia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_dias', models.IntegerField(verbose_name='Días de hospedaje')),
                ('descrip_est', models.CharField(max_length=60, verbose_name='Descripción')),
                ('monto_total', models.IntegerField(verbose_name='Monto total')),
                ('fech_pago', models.DateField(verbose_name='fecha pago')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.reserva')),
                ('valor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tarifa')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.region'),
        ),
    ]
