# Generated by Django 4.0.5 on 2023-05-31 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacuna',
            name='f_pet',
        ),
    ]
