# Generated by Django 4.0.5 on 2023-05-31 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ficha_pet_vacunas_alter_comuna_nombre_com_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha_pet',
            name='vacunas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.vacuna'),
        ),
    ]
