# Generated by Django 4.0.5 on 2023-05-31 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_ficha_pet_vacunas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha_pet',
            name='vacunas',
        ),
        migrations.AddField(
            model_name='vacuna',
            name='mascota',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.ficha_pet'),
            preserve_default=False,
        ),
    ]
